# -*- coding: utf-8 -*-
"""labaratornaya_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QW3YpPTqanJNBafxHds-bA8PtEMlvaxZ

#Щерабатенко Кирилл Максимовч ПИ-311
"""

#1
mouth = int(input ("введите месяц(1-12): "))
if mouth == 1:
  print("январь")
if mouth == 2:
  print("февраль")
if mouth == 3:
  print("март")
if mouth == 4:
  print("апрель")
if mouth == 5:
  print("май")
if mouth == 6:
  print("июнь")
if mouth == 7:
  print("июль")
if mouth == 8:
  print("август")
if mouth == 9:
  print("сентябрь")
if mouth == 10:
  print("октябрь")
if mouth == 11:
  print("ноябрь")
if mouth == 12:
  print("декабрь")

#2
n = int(input("введите число: "))
if n%2==0:
  print("четное ", n)
else:
  print("нечетное ", n)

#3
n = int(input("введите число: "))
if n >= 40:
  print("stonks")
elif n <= 39:
  print("not stonks")

#4
def is_year_leap(n):
  if n % 4 == 0 and n % 100 != 0 or n % 400 == 0:
    return True
  else: return False
d = int(input("Введите год: "))
print(is_year_leap(d))

#5
def is_prime(n):
  if n < 2:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
    else:
      return True
n = int(input("Введите число: "))
print(is_prime(n))

#6
first = int(input("Введите 1-e число: "))
second = int(input("Введите 2-e число: "))

low = -(138 / 2) ** 1.3
hight = (-69 / (28 ** 5.1)) * 4

if first > second * 3.6 or (low <= second <= hight):
  temp = first
  first = second
  second = temp
  print("y")
else:
  print("n")
print(f"1-e: {first}")
print(f"2-e: {second}")

#7
n1 = int(input("Введите 1-e число: "))
n2 = int(input("Введите 2-e число: "))
n3 = int(input("Введите 3-e число: "))
n4 = int(input("Введите 4-e число: "))
n5 = int(input("Введите 5-e число: "))
numbers = [n1, n2, n3, n4, n5]
unic_num = set(numbers)
if len(numbers) == len(unic_num):
  print("unic")
else:
  print("unnic")
chetnie = 0
otrichatelni = 0
v_promejutke = 0
for i in numbers:
  if i % 2 == 0:
    chetnie = chetnie + 1
  if i < 0:
    otrichatelni = otrichatelni + 1
  if -256 <= i <= 1024:
    v_promejutke = v_promejutke + 1
print(f"количество четных чисел = {chetnie}")
print(f"количество отрицательных чисел = {otrichatelni}")
print(f"количество в промежутках = {v_promejutke}")

#8
a = int(input("Введите a: "))
b = int(input("Введите b: "))
c = int(input("Введите c: "))
n = ((a ** 2 + b ** 3) / c + 3) / 4
if n % 2 == 0:
  print("ответ явлется четным числом")
else:
  print("ответ явлется нечетным числом")
print(f"ответ: {n}")