# -*- coding: utf-8 -*-
"""labaratornaya_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kU9cJjPCVgTFEsA9dIoNB3fxRGG8u7A6
"""

# 1 Щербатенко К.М. ПИ-311
a = 5
b = int(input("b= "))
print(a*b)

#2
a = int(input("a= "))
b = int(input("b= "))
print((a+b)**2)

#3
a = 15
b = 10
c = int(input("c= "))
print((a+b)/c)

#4
a = int(input("a= "))
b = int(input("b= "))
print(a**2 + 2*a*b + b**2)

#5
a = int(input("a= "))
b = int(input("b= "))
c = int(input("c= "))
p = a + b + c
half = (a + b + c) / 2
S = ((half * (half - a) * (half - b) * (half - c)) ** 0.5)
print("P=", p)
print("S=", S)

#6
a = int(input("a= "))
b = int(input("b= "))
print(((a ** 3 + 14) / 5)* b)

#7
a = int(input("a= "))
n = int(input("n= "))
print(int((a ** 2) / n))

#8
a = float(input("a= "))
b = float(input("b= "))
print(int(a%b))
a = int(input("a= "))
b = int(input("b= "))
if a > 0 and b > 0:
  print(a*b)
else:
  print("а или b не натуральные")
a = int(input("a= "))
b = int(input("b= "))
0
if a > 0 and b > 0:
  print(a % b)
else:
  print("а или b не натуральные")

#задача повышеной сложности (1)
n = int(input("колличество секунд= "))
print("дней= ", n/3600/24)
print("часов= ", n/3600)
print("ceкунд= ", n/60)

#задача повышеной сложности (2)
n = int(input("целое n= "))
nn = n * 11
nnn = n * 111
r = int(n) + int(nn) + int(nnn)
print("n + nn + nnn = ", r)